cap-md089/evmplus-v6

packages/common-lib/src/typings/types.ts
=> fix: fixed code to match data

.github/workflows/build-and-test.yaml, docker-compose.test.yml, packages/server-jest-config/src/conf.ts, packages/server-jest-config/src/index.ts, packages/server-jest-config/test-data/setup-schema.sh
This pull request will be used to pull all the remaining code off of Development and merge it directly into master so that features branches can be used from now on
=> Final Development Pull Request

.github/workflows/build-and-test.yaml, Dockerfile, docker-compose.test.yml, packages/client/.eslintignore, packages/client/package.json, packages/client/src/App.tsx, packages/client/src/__tests__/components/AttendanceView.test.tsx, packages/client/src/__tests__/components/forms/AttendanceForm.test.tsx, packages/client/src/__tests__/pages/events/EventViewer.test.tsx, packages/client/src/components/AttendanceView.tsx, packages/client/src/components/ErrorHandler.tsx, packages/client/src/components/PageRouter.tsx, packages/client/src/components/forms/SimpleForm.tsx, packages/client/src/components/forms/usable-forms/AttendanceForm.tsx, packages/client/src/globals.tsx, packages/client/src/lib/apis.ts, packages/client/src/lib/error.ts, packages/client/src/pages/events/EventViewer.tsx, packages/client/src/setupTests.js, packages/client/tsconfig.json, packages/common-lib/src/test/data.ts, yarn.lock
affects: client, common-lib
fixed attendance form submit button not acting
fixed crash in EventViewer that resulted from
improper handling of new attendance records
added client unit tests
ISSUES CLOSED: #171
=> fix(client): fixed attendance sign up button not working

packages/client/src/__tests__/pages/events/AttendanceMultiAdd.test.tsx, packages/client/src/pages/events/AttendanceMultiAdd.tsx, packages/server/src/api/events/events/eventviewer.ts
affects: client, evmplus-org-server
ISSUES CLOSED: #176
=> fix(client): fixed attendancemultiadd page crash on load

packages/client/src/pages/calendars/DesktopCalendar.tsx
=> fix(client): fix duplicate days on november calendar

packages/client/src/pages/events/EventViewer.tsx
=> fix(client): added meals information to event viewer

Dockerfile
=> fix: fixed cronjob syntax error

packages/client/src/pages/admin/pages/EmailList.tsx
=> fix(client): fixed the email list not filtering on last names

packages/common-lib/src/renderers/reports/sqr601.ts
affects: common-lib  first fix didn't propagate
=> feat(common): improved visibility for prospective members in sqr60-1

packages/client/src/pages/admin/pages/RegEdit.tsx, packages/common-lib/src/test/data.ts, packages/common-lib/src/typings/types.ts, packages/server-common/src/Registry.ts
Added "Unit Name" to registry entries for use in squadron reports and other areas.
=> New registry

packages/common-lib/src/renderers/reports/sqr601.ts, packages/common-lib/src/typings/types.ts, packages/server-common/src/member/members/cap/NHQMember.ts
affects: common-lib, server-common
ISSUES CLOSED: #201
=> fix(common, server-common): fixed inaccurate PT date expire in report HFZ data

packages/common-lib/src/renderers/reports/sqr601.ts, packages/common-lib/src/typings/types.ts, packages/server-common/src/member/members/cap/NHQMember.ts
affects: common-lib, server-common
=> refactor(common-lib): changed interface to use MaybeObj over array

packages/server/src/api/member/promotionrequirements/account.ts
=> fix(server): fixed an \`or\` and \`and\` being swapped

packages/server-common/src/capwatch-modules/cadethfzinformation.ts
affects: server-common
ISSUES CLOSED: #214
=> fix(server-common): only one HFZ record is imported on CAPWATCH import

packages/client/src/pages/account/RequestPasswordReset.tsx, packages/client/src/pages/account/RequestUsername.tsx, packages/common-lib/src/lib/Member.ts, packages/server-common/src/member/pam/Account.ts, packages/server-common/src/member/pam/index.ts, packages/server-common/src/sendEmail.ts, packages/server/src/api/member/account/nhq/requestaccount.ts
Updated some error messages and information to help communicate to users.
=> Useraccountcreate

scripts/init-nginx-ssl.sh
=> fix: fixed event subdomains being excluded

packages/common-lib/src/renderers/reports/sqr6020.ts
=> fix(client): fixed getnextmonth code return NaN

packages/server-common/src/sendEmail.ts
Updated html email colors to improve contrast and readability.
=> Fixhtmlemail

Dockerfile, cronjobs/download.sh, cronjobs/start-crond.sh, packages/server-common/src/Members.ts, packages/util-cli/src/downloadCapwatchInContainer.ts
Fixed account lookup and cron job CAPWATCH downloads
=> Save capwatch downloads

packages/client/src/pages/admin/pluggables/FindMember.tsx, packages/client/src/pages/admin/pluggables/FlightContact.tsx, packages/server/src/api/member/flights/flightbasic.ts, packages/server/src/api/member/membersearch.ts
updated contact view to element leader and first sergeant and expanded find member to include members in unit with a duty position
=> Contactview

packages/client/src/pages/admin/pages/TemporaryDutyPosition.tsx, packages/client/src/pages/admin/pluggables/FlightContact.tsx, packages/client/src/pages/admin/pluggables/Reports.tsx, packages/client/src/pages/admin/pluggables/SiteAdmin.tsx, packages/common-lib/src/lib/Events.ts, packages/common-lib/src/typings/apis/member/flight.ts, packages/discord-bot/src/data/setupUser.ts, packages/server/src/api/member/flights/flightbasic.ts, packages/server/src/api/member/flights/flightmembers.ts, packages/server/src/api/member/promotionrequirements/account.ts
=> fix: updates the duty position to match capnhq

packages/common-lib/src/lib/iter.ts, packages/discord-bot/package.json, packages/discord-bot/src/cli/notifyRole.ts, packages/discord-bot/src/cli/registerCommands.ts, packages/discord-bot/src/cli/updateServers.ts, packages/discord-bot/src/commands/attendancerecord.ts, packages/discord-bot/src/data/getMember.ts, packages/discord-bot/src/data/getTeamRole.ts, packages/discord-bot/src/data/setupDiscordServer.ts, packages/discord-bot/src/data/setupUser.ts, packages/discord-bot/src/index.ts, types/node:child_process/index.d.ts, types/node:events/index.d.ts, types/node:https/index.d.ts, types/node:stream/index.d.ts, types/node:worker_threads/index.d.ts, yarn.lock
Replaced text commands with slash commands in the Discord bot
FIXES: #250
=> r-a303931/fix discord command

packages/client/src/pages/admin/pluggables/FindMember.tsx
=> feat(client): added a CAPID display for the find member function

packages/client/src/components/flightassign/FlightMember.tsx, packages/client/src/pages/admin/pages/FlightAssign.tsx
chicklets on flight assignment page.  Could probably figure out how to color code, but this implementation is sufficient to convey the data.
ISSUES CLOSED: #256
=> Cadetdutycolors

packages/client/src/pages/admin/pluggables/Reports.tsx, packages/client/src/pages/events/EventViewer.tsx, packages/common-lib/src/renderers/spreadsheets/index.ts, packages/common-lib/src/renderers/spreadsheets/sqr6020.ts
Added SQR 60-20 report as a downloadable spreadsheet
=> Reportspreadsheets

packages/server-common/src/member/pam/Auth.ts, packages/server/src/api/signin.ts
affects: evmplus-org-server, server-common
=> feat(server): made MFA unnecessary for service signins

packages/discord-bot/src/data/setupUser.ts
=> fix(discord-bot): added CAC representatives to Cadet Support Staff role group

packages/client/src/pages/calendars/DesktopCalendar.tsx, packages/client/src/pages/calendars/MobileCalendar.tsx
fix: add calendar event color code legend.
FIXES: #36
=> fix(client): add calendar event color code legend.

.vscode/settings.json, cronjobs/crontab, packages/client/src/pages/admin/pluggables/FindMember.tsx, packages/client/src/pages/events/EventViewer.tsx, packages/common-lib/src/renderers/spreadsheets/AttendanceXlsx.ts, packages/common-lib/src/typings/apis/events/events.ts, packages/common-lib/src/typings/apis/member/index.ts, packages/common-lib/src/typings/schemas.ts, packages/common-lib/src/typings/types.ts, packages/server-common/src/ImportCAPWATCHFile.ts, packages/server-common/src/capwatch-modules/commanders.ts, packages/server-common/src/capwatch-modules/orgcontact.ts, packages/server-common/src/member/members/cap/index.ts, packages/server/src/api/events/events/eventviewer.ts, packages/server/src/api/member/membersearch.ts
Incorporate unit commander, unit name, and unit contact information in attendance spreadsheet download
=> Unit information in attendance download

packages/client/src/pages/admin/pluggables/Reports.tsx, packages/common-lib/src/renderers/spreadsheets/index.ts, packages/common-lib/src/renderers/spreadsheets/sqr601.ts
=> feat(client, common-lib): added spreadsheet download for sqr 60-1

packages/apis/src/index.ts, packages/client/src/components/PageRouter.tsx, packages/client/src/pages/Main.tsx, packages/client/src/pages/admin/pluggables/Su.tsx, packages/client/src/pages/changelog/ChangeLog.tsx, packages/common-lib/src/typings/apis/changelog.ts, packages/common-lib/src/typings/apis/index.ts, packages/common-lib/src/typings/schemas.ts, packages/common-lib/src/typings/types.ts, packages/server-common/src/ChangeLog.ts, packages/server-common/src/index.ts, packages/server/src/api/changelog/add.ts, packages/server/src/api/changelog/get.ts, packages/server/src/api/changelog/index.ts, packages/server/src/api/index.ts, packages/server/src/getAPIRouter.ts
affects: apis, client, common-lib, evmplus-org-server, server-common
ISSUES CLOSED: #275
=> feat(all): added changelog (release notes) add and display

packages/client/src/pages/events/EventLinkList.tsx, packages/common-lib/src/renderers/spreadsheets/AttendanceXlsx.ts, packages/common-lib/src/renderers/spreadsheets/EventListXlsx.ts, packages/common-lib/src/renderers/spreadsheets/index.ts, packages/common-lib/src/renderers/spreadsheets/sqr601.ts, packages/common-lib/src/renderers/spreadsheets/sqr6020.ts
Download event listing in xlsx format
=> Event list download

packages/server/src/api/events/events/listupcoming.ts
affects: evmplus-org-server
ISSUES CLOSED: #280
=> fix(server): fixed linked events do not appear in upcoming events

packages/client/src/components/forms/usable-forms/AttendanceForm.tsx
fixed warning popping up for academic requirements when modifying
attendance records
=> fix(client): fixed erroneous warning display

packages/server/src/api/events/attendance/addattendance.ts
=> fix(server): fixed which email was used to send out sign up emails

packages/server/src/api/events/events/listupcoming.ts
=> fix(server): fixed upcoming events list to include linked events

packages/client/src/pages/calendars/DesktopCalendar.tsx
=> feat(client): added a name bubble when hovering over a calendar item

packages/server-common/src/index.ts, packages/server-common/src/sendEmail.ts, packages/server/src/api/events/attendance/addattendance.ts, packages/server/src/api/events/attendance/addattendancebulk.ts, packages/server/src/api/member/account/capprospective/createprospective.ts, packages/server/src/api/member/account/nhq/requestaccount.ts, packages/server/src/api/member/account/nhq/requestusername.ts, packages/server/src/api/member/account/requestpasswordreset.ts
set all system emails to bcc system emails account
=> System emails

packages/server/src/api/events/attendance/addattendancebulk.ts
=> fix(server): fixed addattendancebulk not sending out signup emails

packages/client/src/components/forms/usable-forms/EventForm.tsx, packages/client/src/pages/account/Signin.tsx
=> feat(client): added links to operator guide in appropriate pages

packages/discord-bot/src/data/getDiscordBackend.ts, packages/server-common/src/Event.ts, packages/server-common/src/defaultBackends.ts, packages/server/src/api/events/debrief/adddebrief.ts, packages/util-cli/src/lib/backend.ts
added function to send an email to all POCs and attendees if an event status is changed to cancelled
=> Grioux neo/send cancel email

packages/server/src/api/events/attendance/deleteattendance.ts, packages/server/src/api/events/attendance/modifyattendance.ts
affects: evmplus-org-server
ISSUES CLOSED: #302
=> fix(server): fixed attendance delete/modify failure

packages/client/src/pages/events/ScanAdd.tsx
=> feat(client): include event information on scan add page

packages/client/src/pages/admin/pluggables/Reports.tsx
=> fix(client): fix filename for report spreadsheet download

packages/server-common/src/ImportCAPWATCHFile.ts, packages/util-cli/src/importCapwatch.ts
Updated logging for import CAPWATCH
=> updated logging for import CAPWATCH

.github/workflows/build-and-test.yaml, Dockerfile, packages/client/src/components/flightassign/FlightMember.tsx, packages/client/src/pages/admin/pages/FlightAssign.tsx
=> feat(client):modified flight assign page to indicate specific OPS duties

packages/server-common/src/capwatch-modules/cadethfzinformation.ts, packages/server-common/src/capwatch-modules/mbrachievement.ts
=> fix(server-common): added deletions for HFZ and achievement data on import

packages/client/src/pages/admin/pages/EmailList.tsx
colors are based off of expiration date relative to when the page is viewed
=> feat: added color filtering to emaillist

cronjobs/crontab
=> feat(cronjobs): changed the time of the CAPWATCH download

packages/client/src/components/forms/usable-forms/EventForm.tsx
Removed a line of code that was trying to modify an immutable array. Intended functionality preserved without any code additions.
ISSUES CLOSED: #371
=> fix(client): fix bug that disabled adding members to event

packages/common-lib/src/renderers/reports/sqr601.ts, packages/common-lib/src/renderers/spreadsheets/sqr601.ts, packages/server-common/src/member/members/cap/NHQMember.ts
Wingman course completion credit was not reflected on the SQR 60-1 report prevously.  Still inconsistent results, though improved.  Keeping issue #383 open until consistent results achieved.
=> fix: added check for wingman course to be included in credit for C/AB

packages/client/src/components/form-inputs/POCInput.tsx
POC section had a checkbox labeled "Display publicly".  This checkbox value did not change what was displayed.  Checkbox removed.
=> Event form display poc

packages/client/src/components/dialogues/MemberSelectorAsButton.tsx
allows actually modifying the fields
fixes #404
=> fix: take control of filters for memberselector
